# Generated by Django 5.1.3 on 2024-12-10 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_leaverequest_status_alter_leaverequest_leave_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="day",
            name="worked",
        ),
        migrations.AddField(
            model_name="day",
            name="span",
            field=models.CharField(default="1", max_length=255),
            preserve_default=False,
        ),
    ]
